const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gittrace', {
    openFolder: () => ipcRenderer.invoke('dialog:openFolder'),
    openRepo: (p) => ipcRenderer.invoke('git:open', p),
    commitDiff: (p, h) => ipcRenderer.invoke('git:commitDiff', p, h),
    fileDiff: (p, f) => ipcRenderer.invoke('git:fileDiff', p, f),
    fileContent: (p, f) => ipcRenderer.invoke('git:fileContent', p, f),
    fileTree: (p) => ipcRenderer.invoke('git:fileTree', p),
    refreshStatus: (p) => ipcRenderer.invoke('git:refreshStatus', p),
    diffStats: (p, f) => ipcRenderer.invoke('git:diffStats', p, f),
    graphData: (p) => ipcRenderer.invoke('git:graph', p),
    authors: (p) => ipcRenderer.invoke('git:authors', p),
    hotFiles: (p) => ipcRenderer.invoke('git:hotFiles', p),
    recentActivity: (p) => ipcRenderer.invoke('git:recentActivity', p),
    statusMap: (p) => ipcRenderer.invoke('git:statusMap', p),
    dirTree: (p) => ipcRenderer.invoke('git:dirTree', p),
    liveFileContent: (p, f) => ipcRenderer.invoke('git:liveFileContent', p, f),
    saveFile: (p, f, c) => ipcRenderer.invoke('git:saveFile', p, f, c),
    compare: (p, from, to) => ipcRenderer.invoke('git:compare', p, from, to),
    commitFileContent: (p, h, f) => ipcRenderer.invoke('git:commitFileContent', p, h, f),
    changesOverview: (p) => ipcRenderer.invoke('git:changesOverview', p),
    showInFolder: (p) => ipcRenderer.invoke('shell:showInFolder', p),
    openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
    onLiveChange: (cb) => ipcRenderer.on('live:change', (_, d) => cb(d)),
    contextMenu: (opts) => ipcRenderer.invoke('context:menu', opts),
    minimize: () => ipcRenderer.invoke('window:minimize'),
    maximize: () => ipcRenderer.invoke('window:maximize'),
    close: () => ipcRenderer.invoke('window:close'),
    isMaximized: () => ipcRenderer.invoke('window:isMaximized')
});
